DROP TABLE IF EXISTS HistoryLog;
DROP TABLE IF EXISTS PasswordAuthentication;
DROP TABLE IF EXISTS FileTag;
DROP TABLE IF EXISTS SyncedFileVersion;
DROP TABLE IF EXISTS SyncedFile;
DROP TABLE IF EXISTS "User";
