#!/bin/sh
#
# barabasd: Starts the Barabas Daemon
#
# chkconfig:   345 24 02
# description: Barabas server daemon
# processname: barabasd
# pidfile:     /var/run/barabasd.pid

### BEGIN INIT INFO
# Required-Start:    network
# Required-Stop:     network
# Should-Start:      $network $local_fs
# Should-Stop:       $local_fs
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: Starts the barabas daemon
# Description:       Barabas server daemon implements the Barabas protocol.
### END INIT INFO

BARABASD_BIN=/usr/bin/barabasd

if [ "$1" = 'status' ]; then
    test -x $BARABASD_BIN || exit 4
else
    test -x $BARABASD_BIN || exit 5
fi

# Source function library.
. /etc/init.d/functions
. /etc/sysconfig/network

LOCKFILE=/var/lock/subsys/barabasd
PIDFILE=/var/run/barabsd.pid
RETVAL=0

base=${0##*/}

start() {
    # Check that networking is configured.
    [ ${NETWORKING} = "no" ] && exit 1

	echo -n $"Starting Barabas Daemon... "
    daemon --pidfile=${PIDFILE} $BARABSD_BIN
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch ${LOCKFILE}
	return $RETVAL
}

stop() {
    echo -n $"Shutting down Barabas daemon: "
    killproc -p ${PIDFILE} $AVAHI_BIN
    RETVAL=$?
    [ $RETVAL -eq 0 ] && rm -f ${LOCKFILE} ${PIDFILE}
    echo
	return $RETVAL
}

restart() {
	stop
	start
}

RETVAL=0

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status -p ${PIDFILE} $BARABASD_BIN
        RETVAL=$?
	;;
  restart)
	restart
	;;
  condrestart)
  	if [ -f $LOCKFILE ]; then
		restart
	fi
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|condrestart}"
	exit 2
        ;;
esac

exit $RETVAL

