CREATE TABLE SyncedFile (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	fileName VARCHAR(512) NOT NULL
);

CREATE TABLE SyncedFileVersion (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	syncedFileID INTEGER NOT NULL,
	filePointer VARCHAR(512) NOT NULL,
	timeEdited TIMESTAMP NOT NULL,
	timeStored TIMESTAMP NOT NULL,
	FOREIGN KEY(syncedFileID) REFERENCES SyncedFile(ID)
);

CREATE TABLE FileTag (
	fileID INTEGER NOT NULL,
	tagName VARCHAR(512) NOT NULL,
	PRIMARY KEY(fileID, tagName),
	FOREIGN KEY(fileID) REFERENCES SyncedFile(ID)
);
