CREATE TABLE User (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	firstName VARCHAR(64),
	lastName VARCHAR(64),
	email VARCHAR(512) UNIQUE,
	lastLoginTime TIMESTAMP DEFAULT NULL,
	registrationDate DATE
);

CREATE TABLE PasswordAuthentication (
	ID INTEGER,
	userID INTEGER,
	username VARCHAR(64) UNIQUE,
	passwordHash VARCHAR(128),
	passwordSalt VARCHAR(32),
	resetHash VARCHAR(64),
	FOREIGN KEY (userID) REFERENCES User(ID)
);

ALTER TABLE SyncedFile ADD ownerID INTEGER REFERENCES User(ID);
